vich_uploader:
    db_driver: orm

    mappings:
        pdf:
            uri_prefix: '%app.path.pdf%'
            upload_destination: '%kernel.project_dir%/public/%app.path.pdf%'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer
        various_file:
            uri_prefix: '%app.path.files%'
            upload_destination: '%kernel.project_dir%/public/%app.path.files%'
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer